// Expone Lucide como window.lucide importando SOLO los iconos usados.
// Esto mantiene el bundle ligero en lugar de cargar los ~1500 iconos.
import { createIcons } from "lucide";
import {
  AlignLeft,
  Archive,
  ArrowRight,
  Bell,
  BellRing,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCheck,
  CheckCircle2,
  SquareCheckBig,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  CircleX,
  Clock,
  Cloud,
  CornerDownRight,
  Download,
  Ellipsis,
  FilePlus,
  FileText,
  Flag,
  FolderInput,
  GripVertical,
  Inbox,
  Info,
  Keyboard,
  Languages,
  Layers,
  List,
  ListFilter,
  Menu,
  ListOrdered,
  ListPlus,
  ListTodo,
  MessageCircle,
  Palette,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PencilLine,
  Plus,
  Repeat,
  Rows3,
  Search,
  Settings,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  SunMoon,
  Tag,
  Trash2,
  TriangleAlert,
  Upload,
  UserRound,
  X,
} from "lucide";

const icons = {
  AlignLeft,
  Archive,
  ArrowRight,
  Bell,
  BellRing,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCheck,
  CheckCircle2,
  SquareCheckBig,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  CircleX,
  Clock,
  Cloud,
  CornerDownRight,
  Download,
  Ellipsis,
  FilePlus,
  FileText,
  Flag,
  FolderInput,
  GripVertical,
  Inbox,
  Info,
  Keyboard,
  Languages,
  Layers,
  List,
  ListFilter,
  Menu,
  ListOrdered,
  ListPlus,
  ListTodo,
  MessageCircle,
  Palette,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PencilLine,
  Plus,
  Repeat,
  Rows3,
  Search,
  Settings,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  SunMoon,
  Tag,
  Trash2,
  TriangleAlert,
  Upload,
  UserRound,
  X,
};

window.lucide = {
  /** Compatible con la API UMD: acepta opts.nodes, opts.attrs, etc. */
  createIcons: function (opts) {
    createIcons({ icons, ...opts });
  },
};

// Renderiza los iconos data-lucide del HTML estático al cargar el módulo.
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", function () {
    createIcons({ icons });
  });
} else {
  createIcons({ icons });
}
